blank_issues_enabled: false
contact_links:
  - name: Obsidian Dataview Discussions
    url: https://github.com/blacksmithgu/obsidian-dataview/discussions
    about: Please ask and answer questions here.
